# Generated by Django 4.2.18 on 2025-01-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_manager_api", "0002_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="input_data",
            field=models.JSONField(verbose_name="Входные данные"),
        ),
        migrations.AlterField(
            model_name="task",
            name="result",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Результат"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Запланировано"),
                    ("running", "Выполняется"),
                    ("completed", "Выполнено"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("sum_numbers", "сумма чисел"),
                    ("countdown", "обратный отсчет"),
                ],
                default="sum_numbers",
                max_length=15,
                verbose_name="Тип задачи",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
